---
- hosts: odmapp
  vars:
    http_port: 80
    max_clients: 200
  vars_files:
    - group_vars/vars.yml
  remote_user: vagrant
  become: yes
  tasks:
  - name: copy jar
    copy:
      src: /home/vagrant/jenkins_slave/workspace/java-pipeline_master/build/libs/odm-java-pipeline-0.1.0.jar
      dest: .
      owner: vagrant
      group: vagrant
  - name: Run app
    shell: nohup java -jar odm-java-pipeline-0.1.0.jar &